# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-30 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190429_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='uploaded_files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipFile', models.FileField(upload_to=b'')),
            ],
        ),
    ]
